In [9]:
#1. Create a numpy array with numpy.array module and with a data type integer and float.

import numpy as np

In [11]:
arr1=np.array([1,2,3,4],dtype=int)
arr1

array([1, 2, 3, 4])

In [13]:
arr1.dtype

dtype('int32')

In [5]:
type(arr1)

numpy.ndarray

In [6]:
arr2=np.array([1.0,2,3,4])
arr2

array([1., 2., 3., 4.])

In [7]:
arr2.dtype

dtype('float64')

In [8]:
#2. Create numpy arrays that have zero, one, two, three, Four dimensions respectively.
#Also, print the shape and dimensions of the numpy arrays created above

a=np.array(10)
a.shape

()

In [9]:
a.ndim

0

In [10]:
#1 dim

b=np.array([1,2,3,4])
b.shape

(4,)

In [11]:
b.ndim

1

In [12]:
# 2 dim

c=np.array([[1,2,3],[4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
c.shape

(2, 3)

In [14]:
c.ndim

2

In [15]:
#3 dim

d=np.array([1,2,3,4],ndmin=3)

In [16]:
d

array([[[1, 2, 3, 4]]])

In [17]:
# ndim to check dim
# ndmin to assign dim

In [19]:
d=np.array([1,2,3,4],ndmin=10)
d

array([[[[[[[[[[1, 2, 3, 4]]]]]]]]]])

In [20]:
d.ndim

10

In [22]:
#3. Create a 2x2, 3x3, and 4x4 identity matrix using numpy.

# identity()


c=np.array([[[1,2,3],[4,5,6]],[[11,12,13],[14,15,16]]])
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [14, 15, 16]]])

In [23]:
c.ndim

3

In [24]:
c.shape

(2, 2, 3)

In [28]:
a=np.identity(2,dtype="int")
a

array([[1, 0],
       [0, 1]])

In [29]:
b=np.identity(3,dtype="int")
b

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [37]:
c=np.identity(4,dtype="int")*5
c

array([[5, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 5]])

In [31]:
c.dtype

dtype('int64')

In [33]:
x=c.astype("float")
x

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [43]:
#4. Create a numpy array with shape 2x5 that has all the elements as zero.

arr=np.zeros([2,5],dtype=int)
arr


array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [44]:
#5. Create a numpy array that has the shape 3x5 and all the elements are 5.

#full()
#zeros()

arr=np.full([3,5],5)
arr

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [47]:
arr1=np.zeros([3,5],dtype=int)+5
arr1

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [48]:
arr2=np.ones([3,5])*5
arr2

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [55]:
#6. Create a numpy array with random integers in the range 0-100, and the sample size
#should be 25.



a=np.random.randint(0,100,25)
a

array([77,  5, 56,  1, 21, 81, 92, 11,  8,  0, 25,  3,  0, 44,  0, 27, 42,
       22, 59, 30, 64, 65, 74, 11, 63])

In [54]:
np.linspace(0,100,25,dtype="int")

array([  0,   4,   8,  12,  16,  20,  25,  29,  33,  37,  41,  45,  50,
        54,  58,  62,  66,  70,  75,  79,  83,  87,  91,  95, 100])

In [56]:
#7.Create a numpy array with a shape 3x3 that has all elements as 1

In [58]:
a=np.ones([3,3],dtype=int)
a

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [59]:
#8. Create a numpy array in the shape 2x3 with random integers in the range 0-100.
#Reshape the array in the shape 3x2 and print the updated shape of the resultant array.

arr1=np.random.randint(0,100,(2,3))
arr1

array([[79, 62, 38],
       [22, 69, 96]])

In [60]:
x=arr1.reshape(3,2)

In [62]:
print(x.shape)
print(arr1.shape)

(3, 2)
(2, 3)


In [63]:
c = np.random.randint(1,100,[2,3])
a = c.reshape(3,2)


In [64]:
a.shape

(3, 2)

In [25]:
# 9. Create a random array, with the range 0-1000, with a size 50 and
# step 2. Perform the following operations on the same.

# a. Print the first ten elements of the array.
# b. Print the last ten elements of the array
# c. Print the elements from the indexes 10-25
# d. Print the element at the index 22
# e. Print the array using negative indexing.
# f. Print the last ten elements of the array, using negative indexing."""

In [27]:
a=np.random.randint(0,1000,50)
a

array([645, 348, 995, 914, 852,  11,  82, 528, 620, 227, 147, 339, 667,
         3, 574, 138, 521, 834, 670, 304,  76, 485, 852, 893,  48,  69,
       345, 572,  37, 766, 212, 313,  12, 530,  40,  35, 567,  24, 581,
       367, 893, 194, 932, 251,  94,  46, 227, 979, 432, 240])

In [69]:
#1
a[0:10]

array([439, 269, 201, 828, 832,  15, 269, 918, 649, 644])

In [70]:
#2
a[-10:]

array([893, 911, 421, 349, 120, 910, 157, 442, 413, 758])

In [72]:
#3
a[10:26]

array([839, 273, 206, 288, 601, 778, 610, 915, 476, 693, 402, 549, 392,
       121, 704, 401])

In [73]:
#4
a[22]

392

In [79]:
#5

a[::-1]

array([127, 469, 370, 478, 777, 256, 334, 389, 403, 843,  36, 232, 258,
       338,  37, 545, 701, 245, 322, 632, 284,  87, 418, 942, 394, 461,
       664, 902, 256, 498, 554, 452, 538, 464, 134, 946, 636, 802,  16,
       402, 708, 590, 425, 146, 967,  55, 889, 166, 623, 437])

In [80]:
#6
a[-10:]

array([843, 403, 389, 334, 256, 777, 478, 370, 469, 127])

In [15]:
c=np.array([[1,2,3],[4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [84]:
a=[1,2,3,4,5,6]

a[-4:]

[3, 4, 5, 6]

In [17]:
c=np.array([[1,2,3],[4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
#print all the odd numbers in this array c using looping.
c=np.array([[1,2,3],[4,5,6]])
for row in c:
    for element in row:
        if element % 2 != 0:
            print(element)

1
3
5
